---
# Add description/tips for each metric in this section.
# So it could be shown in hover.
Metric Description:

# Define the panel properties and properties of each metric in the panel.
Panel Config:
  id: 700
  title: Wavefront
  data source:
    - metric_table:
        id: 701
        title: Wavefront Launch Stats
        header:
          metric: Metric
          avg: Avg
          min: Min
          max: Max
          unit: Unit
          tips: Tips
        metric:
          Grid Size:
            avg: AVG(grd)
            min: MIN(grd)
            max: MAX(grd)
            unit: Work Items
            tips: 
          Workgroup Size:
            avg: AVG(wgr)
            min: MIN(wgr)
            max: MAX(wgr)
            unit: Work Items
            tips: 
          Total Wavefronts:
            avg: AVG(SPI_CSN_WAVE)
            min: MIN(SPI_CSN_WAVE)
            max: MAX(SPI_CSN_WAVE)
            unit: Wavefronts
            tips: 
          Saved Wavefronts:
            avg: AVG(SQ_WAVES_SAVED)
            min: MIN(SQ_WAVES_SAVED)
            max: MAX(SQ_WAVES_SAVED)
            unit: Wavefronts
            tips: 
          Restored Wavefronts:
            avg: AVG(SQ_WAVES_RESTORED)
            min: MIN(SQ_WAVES_RESTORED)
            max: MAX(SQ_WAVES_RESTORED)
            unit: Wavefronts
            tips: 
          VGPRs:
            avg: AVG(vgpr)
            min: MIN(vgpr)
            max: MAX(vgpr)
            unit: Registers
            tips: 
          SGPRs:
            avg: AVG(sgpr)
            min: MIN(sgpr)
            max: MAX(sgpr)
            unit: Registers
            tips: 
          LDS Allocation:
            avg: AVG(lds)
            min: MIN(lds)
            max: MAX(lds)
            unit: Bytes
            tips: 
          Scratch Allocation:
            avg: AVG(scr)
            min: MIN(scr)
            max: MAX(scr)
            unit: Bytes
            tips: 

    - metric_table:
        id: 702
        title: Wavefront Runtime Stats
        header:
          metric: Metric
          avg: Avg
          min: Min
          max: Max
          unit: Unit
          tips: Tips
        metric:
          Kernel Time (Nanosec):
            avg: AVG((EndNs - BeginNs))
            min: MIN((EndNs - BeginNs))
            max: MAX((EndNs - BeginNs))
            unit: ns
            tips: 
          Kernel Time (Cycles):
            avg: AVG(GRBM_GUI_ACTIVE)
            min: MIN(GRBM_GUI_ACTIVE)
            max: MAX(GRBM_GUI_ACTIVE)
            unit: Cycle
            tips: 
          Instr/wavefront:
            avg: AVG((SQ_INSTS / SQ_WAVES))
            min: MIN((SQ_INSTS / SQ_WAVES))
            max: MAX((SQ_INSTS / SQ_WAVES))
            unit: Instr/wavefront
            tips: 
          Wave Cycles:
            avg: AVG(((4 * SQ_WAVE_CYCLES) / $denom))
            min: MIN(((4 * SQ_WAVE_CYCLES) / $denom))
            max: MAX(((4 * SQ_WAVE_CYCLES) / $denom))
            unit: (Cycles + $normUnit)
            tips: 
          Dependency Wait Cycles:
            avg: AVG(((4 * SQ_WAIT_ANY) / $denom))
            min: MIN(((4 * SQ_WAIT_ANY) / $denom))
            max: MAX(((4 * SQ_WAIT_ANY) / $denom))
            unit: (Cycles + $normUnit)
            tips: 
          Issue Wait Cycles:
            avg: AVG(((4 * SQ_WAIT_INST_ANY) / $denom))
            min: MIN(((4 * SQ_WAIT_INST_ANY) / $denom))
            max: MAX(((4 * SQ_WAIT_INST_ANY) / $denom))
            unit: (Cycles + $normUnit)
            tips: 
          Active Cycles:
            avg: AVG(((4 * SQ_ACTIVE_INST_ANY) / $denom))
            min: MIN(((4 * SQ_ACTIVE_INST_ANY) / $denom))
            max: MAX(((4 * SQ_ACTIVE_INST_ANY) / $denom))
            unit: (Cycles + $normUnit)
            tips: 
          Wavefront Occupancy:
            avg: AVG((SQ_ACCUM_PREV_HIRES / GRBM_GUI_ACTIVE))
            min: MIN((SQ_ACCUM_PREV_HIRES / GRBM_GUI_ACTIVE))
            max: MAX((SQ_ACCUM_PREV_HIRES / GRBM_GUI_ACTIVE))
            unit: Wavefronts
            coll_level: SQ_LEVEL_WAVES
            tips:  
