# This is a basic workflow to help you get started with Actions

name: RHEL 8

# Controls when the workflow will run
on:
  push:
    branches: [ amd-mainline, amd-staging, release/** ]
  pull_request:
    branches: [ amd-mainline, amd-staging, release/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
       image: colramos/target-images:rhel8
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install baseline OS dependencies
        run: |
          yum -y install git
          yum -y install python39
          yum -y install cmake3
          yum -y install which
          yum -y install glibc-langpack-en
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python prereqs
        run: |
          python3.9 -m pip install -r requirements.txt
          python3.9 -m pip install -r requirements-test.txt
      - name: Configure and install
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/opt/rocprofiler-compute -DPYTEST_NUMPROCS=4 ..
          make install
      - name: CTest- Analyze Commands
        run: |
          cd build
          ctest --verbose -R test_analyze_commands
      - name: CTest- Analyze Workloads
        run: |
          cd build
          ctest --verbose -R test_analyze_workloads
