# This is a basic workflow to help you get started with Actions

name: Ubuntu 20.04

# Controls when the workflow will run
on:
  push:
    branches: [ main, dev, ci-reorg ]
  pull_request:
    branches: [ main, dev, ci-reorg ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
       image: rocm/dev-ubuntu-22.04:5.3
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Cancel any previous runs
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
      - name: Install baseline OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          sudo apt-get install -y python3-pip
          sudo apt-get install -y cmake
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
      - name: Install Python prereqs
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install pyinstaller pytest pytest-cov mock
      - name: Configure and install
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/opt/omniperf ..
          make install
      - name: CTEST- Analyze Commands
        run: |
          cd build
          ctest --verbose -R test_analyze_commands
      - name: CTEST- Analyze Workloads
        run: |
          cd build
          ctest --verbose -R test_analyze_workloads test_saved_analysis
