# This is a basic workflow to help you get started with Actions

name: Ubuntu 22.04

on:
  push:
    branches: [ amd-mainline, amd-staging, release/** ]
  pull_request:
    branches: [ amd-mainline, amd-staging, release/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
       image: rocm/dev-ubuntu-22.04:5.7.1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install baseline OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          sudo apt-get install -y python3-pip
          sudo apt-get install -y cmake
          sudo apt-get install -y locales
          sudo locale-gen en_US.UTF-8
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python prereqs
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install -r requirements-test.txt
      - name: Configure and install
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/opt/rocprofiler-compute -DPYTEST_NUMPROCS=4 ..
          make install
      - name: CTest- Analyze Commands
        run: |
          cd build
          ctest --verbose -R test_analyze_commands
      - name: CTest- Analyze Workloads
        run: |
          cd build
          ctest --verbose -R test_analyze_workloads
